### ISSUE TITLE
update RLs

### ISSUE THREAD

**Issue by stopfstedt** [throneteki/throneteki-json-data#110]
see https://agot.cards/2021/07/16/restricted-list-updates-and-more/

**Comment by stopfstedt** [comment]
couple of issues here:

Melee list for Valyrian is missing. From previous conversations with the G.O.T. I assume that the last, Conclave-issued RL for Melee is the pairing here. But needs to be confirmed. Needs clarification on whether Redesigns are part of Valyrian Melee RL now too - in which case G.O.T. needs to communicate this.
For context: _ThronesDB requires a pairing of Melee and Joust RLs._

The versions of the new RLs need to be aligned. Joust says v2.2, Melee says v1.0.

**Comment by stopfstedt** [comment]
> The versions of the new RLs need to be aligned. Joust says v2.2, Melee says v1.0. My suggestion would be a reset to v1.0 for both. To re-state my point from above - they really should be treated as two parts of the same thing.

feedback from Storm/G.O.T on the versioning issue:

> To be clear, it would be:
Valyrian Joust - v 1.0
Joust - v 1.0
Melee - v 1.0

**Comment by ystros** [comment]
Reseting all of them to v1.0 makes sense to me, as does keeping Joust + Melee RLs grouped together.

Throneteki divides out the redesigns vs original FFG RLs using the `cardset` property, so we could likely do that to distinguish Valyrian vs Standard.

I think we've both been using the Issuer name to distinguish between the existing Redesigns and Conclave, which is being stored in the Issuer field. But for Standard vs Valyrian, they have the same issuer (A.G.O.T). So we may need to distinguish between them some other way.

**Comment by stopfstedt** [comment]
> Throneteki divides out the redesigns vs original FFG RLs using the cardset property, so we could likely do that to distinguish Valyrian vs Standard.

sounds good. as i mentioned out of band, ThronesDB is currently not processing this property at all, so feel free to change things to your needs (I'll park the PR directly in this repo rather than my fork so that it can be edited by anyone with write access to this repo).

> I think we've both been using the Issuer name to distinguish between the existing Redesigns and Conclave, which is being stored in the Issuer field. But for Standard vs Valyrian, they have the same issuer (A.G.O.T). So we may need to distinguish between them some other way.

Agreed. Will add new `label` or `title` attribute to those lists, then back-fill it what's currently generated with the generated labels.
