### ISSUE TITLE
 Ser Jacelyn Bywater: card image has wrong cost

### ISSUE THREAD

**Issue by stopfstedt** [throneteki/throneteki-json-data#127]
see https://thronesdb.com/card/21008

will need a new image upload and a corresponding URL change in the cards data i suppose.

**Comment by ystros** [comment]
I'm seeing the cost in the card data match the image - both say Cost 5. Unless you're saying the data is wrong as well?
<img width="1137" alt="Screen Shot 2021-11-17 at 8 26 56 PM" src="https://user-images.githubusercontent.com/145077/142352197-76ff5c21-7148-431a-a7b0-c5cfbce88de9.png">

**Comment by EvadLhorg** [comment]
It is not the cost that is wrong but the artwork of the card. my referenced PR will update the artist, sent @ystros  a pm on Discord with the link to the new card image to upload.

**Comment by stopfstedt** [comment]
duh, of course. got myself confused there.

**Comment by ystros** [comment]
New image uploaded and CDN cache purged.
<img width="1174" alt="Screen Shot 2021-11-18 at 10 59 19 AM" src="https://user-images.githubusercontent.com/145077/142479551-703a5a1f-e127-4077-a4df-93da5b9db74a.png">
