### ISSUE TITLE
Add support for new kind of pod restriction in the RL

### ISSUE THREAD

**Issue by EvadLhorg** [throneteki/throneteki-json-data#95]
There has been some discussion in the design team regarding upcoming restricted lists and we would like to be able to define pods that have no restricted card as an "anchor" card but only consist of cards that are not allowed to be played together, while being not-restricted by themselves.
For example a hypothetical pod could be The Roseroad and At the Gates. You wouldn't be allowed to play these together in a deck. Both of those cards are not restricted, so you would be able to play The Roseroad+1 card each from different pods or At The Gates+1 card each from different pods.
From a code perspective, we would need to keep downward compatibility with the "old" pods and also have a look at throneteki-deck-helper to make the necessary changes there to handle pods without restricted cards.

**Comment by stopfstedt** [comment]
this should be doable in TDB without too much hassle.

suggesting we either make the `restricted` attribute in the `pod` definition nullable or optional. 

https://github.com/throneteki/throneteki-json-data/blob/master/restricted-list.schema.json#L14

**Comment by ystros** [comment]
Commit that implements this on the deck helper:
https://github.com/throneteki/throneteki-deck-helper/commit/15649f81ca9ca7f7a61b3eaf19cab3a01bd312cf
